### ISSUE TITLE
Bug: Console Market 无法安装 puppeteer

### ISSUE THREAD

**Issue by HuanLinOTO** [koishijs/koishi-plugin-puppeteer#28]
### Describe the bug

![image](https://user-images.githubusercontent.com/94176676/216038644-205f46be-8184-4fd8-b5ae-42f368826bb6.png)
安装 github 插件告诉我pptr已安装
![image](https://user-images.githubusercontent.com/94176676/216038778-1fd4350c-1cd4-461f-ad44-24204060485d.png)
紧接着去搜索 pptr 告诉我未安装 点进去又是已安装
![image](https://user-images.githubusercontent.com/94176676/216038835-f3704e16-b372-49f0-897e-d726191c0f09.png)
插件配置也找不到 pptr
![image](https://user-images.githubusercontent.com/94176676/216039358-e822c6de-165c-4978-b8a2-79fad5450839.png)
但是通过 yarn 可以发现其实是安装了 pptr 的

删去 `node_modules` 加以多次重启后解决

### Steps to reproduce

1. 润一个新的 koishi-pttr docker 
2. 安装 github 插件 ( 可能非必须 )
3. 去看 pptr 插件是否安装

### Expected behavior

显示 pptr 已安装

### Screenshots

https://pastebin.com/ca1nYhr0

### Versions
```yaml
System:
    OS: Linux 5.4 Alpine Linux
    CPU: (8) x64 Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz
    GPU: Tesla V100-SXM2-32GB
    RAM: 22286MiB / 39359MiB
Binaries:
    Node: 18.13.0
    Yarn: 1.22.19

Koishi:
    Core: 4.11.2
    Console: 5.1.10
```

### Additional context

此问题为尝试复现 https://github.com/koishijs/koishi-plugin-github/issues/22 时出现的
~~可以顺便看看吗~~

---
edit: 转移 log
